# Generated by Django 4.2.7 on 2025-12-02 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzmat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('individual', 'Физическое лицо'), ('company', 'Компания')], default='individual', max_length=20, verbose_name='Тип аккаунта'),
        ),
        migrations.AddField(
            model_name='user',
            name='company_address',
            field=models.TextField(blank=True, null=True, verbose_name='Адрес компании'),
        ),
        migrations.AddField(
            model_name='user',
            name='company_description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание компании'),
        ),
        migrations.AddField(
            model_name='user',
            name='company_director',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Директор'),
        ),
        migrations.AddField(
            model_name='user',
            name='company_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email компании'),
        ),
        migrations.AddField(
            model_name='user',
            name='company_inn',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ИНН'),
        ),
        migrations.AddField(
            model_name='user',
            name='company_legal_address',
            field=models.TextField(blank=True, null=True, verbose_name='Юридический адрес'),
        ),
        migrations.AddField(
            model_name='user',
            name='company_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Название компании'),
        ),
        migrations.AddField(
            model_name='user',
            name='company_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон компании'),
        ),
        migrations.AddField(
            model_name='user',
            name='company_website',
            field=models.URLField(blank=True, null=True, verbose_name='Сайт компании'),
        ),
    ]
