# Generated by Django 4.2.7 on 2025-12-10 23:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uzmat', '0002_user_account_type_user_company_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='uzmat.category', verbose_name='Родительская категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_type', models.CharField(choices=[('rent', 'Аренда'), ('sale', 'Продажа'), ('service', 'Услуги'), ('parts', 'Запчасти')], max_length=20, verbose_name='Тип объявления')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL')),
                ('description', models.TextField(verbose_name='Описание')),
                ('equipment_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Тип техники')),
                ('brand', models.CharField(blank=True, max_length=100, null=True, verbose_name='Марка')),
                ('model', models.CharField(blank=True, max_length=100, null=True, verbose_name='Модель')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='Год выпуска')),
                ('service_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Название услуги')),
                ('part_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Название запчасти')),
                ('part_equipment_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Для какого типа техники')),
                ('part_brand', models.CharField(blank=True, max_length=100, null=True, verbose_name='Марка для запчасти')),
                ('part_model', models.CharField(blank=True, max_length=100, null=True, verbose_name='Модель для запчасти')),
                ('country', models.CharField(default='kz', max_length=10, verbose_name='Страна')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Цена')),
                ('currency', models.CharField(choices=[('kzt', '₸ KZT'), ('uzs', 'сум UZS'), ('rub', '₽ RUB'), ('byn', 'Br BYN')], default='kzt', max_length=10, verbose_name='Валюта')),
                ('price_type', models.CharField(blank=True, choices=[('per-hour', 'За час'), ('per-day', 'За день'), ('per-month', 'За месяц'), ('fixed', 'Договорная')], max_length=20, null=True, verbose_name='Тип цены')),
                ('with_operator', models.BooleanField(default=False, verbose_name='С оператором')),
                ('min_order', models.CharField(blank=True, max_length=100, null=True, verbose_name='Минимальный заказ')),
                ('power', models.IntegerField(blank=True, null=True, verbose_name='Мощность (л.с.)')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Вес (т)')),
                ('condition', models.CharField(blank=True, choices=[('new', 'Новое'), ('excellent', 'Отличное'), ('good', 'Хорошее'), ('satisfactory', 'Удовлетворительное')], max_length=20, null=True, verbose_name='Состояние')),
                ('hours', models.IntegerField(blank=True, null=True, verbose_name='Часы работы')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('views_count', models.IntegerField(default=0, verbose_name='Количество просмотров')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='uzmat.category', verbose_name='Категория')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertisements', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='advertisements/', verbose_name='Изображение')),
                ('is_main', models.BooleanField(default=False, verbose_name='Главное изображение')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='uzmat.advertisement', verbose_name='Объявление')),
            ],
            options={
                'verbose_name': 'Фотография объявления',
                'verbose_name_plural': 'Фотографии объявлений',
                'ordering': ['is_main', 'order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='uzmat.advertisement', verbose_name='Объявление')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Избранное',
                'verbose_name_plural': 'Избранное',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'advertisement')},
            },
        ),
        migrations.AddIndex(
            model_name='advertisement',
            index=models.Index(fields=['ad_type', 'is_active'], name='uzmat_adver_ad_type_d09df3_idx'),
        ),
        migrations.AddIndex(
            model_name='advertisement',
            index=models.Index(fields=['city', 'country'], name='uzmat_adver_city_d3347d_idx'),
        ),
        migrations.AddIndex(
            model_name='advertisement',
            index=models.Index(fields=['-created_at'], name='uzmat_adver_created_0dbded_idx'),
        ),
    ]
