# Generated by Django 4.2.7 on 2025-12-13 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzmat', '0003_category_advertisement_adimage_favorite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adimage',
            name='image',
            field=models.ImageField(help_text='Загрузите изображение для объявления', upload_to='advertisements/', verbose_name='Изображение'),
        ),
        migrations.AlterModelTable(
            name='adimage',
            table='uzmat_adimage',
        ),
    ]
