# Generated by Django 4.2.7 on 2025-12-14 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzmat', '0004_alter_adimage_image_alter_adimage_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='image',
            field=models.ImageField(blank=True, help_text='Загрузите фотографию для объявления', null=True, upload_to='advertisements/', verbose_name='Фотография объявления'),
        ),
        migrations.DeleteModel(
            name='AdImage',
        ),
    ]
