# Generated by Django 4.2.7 on 2025-12-14 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uzmat', '0005_advertisement_image_delete_adimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertisementImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='advertisements/', verbose_name='Фотография')),
                ('is_main', models.BooleanField(default=False, verbose_name='Главное изображение')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='uzmat.advertisement', verbose_name='Объявление')),
            ],
            options={
                'verbose_name': 'Фотография объявления',
                'verbose_name_plural': 'Фотографии объявлений',
                'ordering': ['is_main', 'order', 'created_at'],
            },
        ),
    ]
