# Generated by Django 4.2.7 on 2025-12-15 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzmat', '0006_advertisementimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='is_promoted',
            field=models.BooleanField(default=False, verbose_name='Продвинуто'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='promoted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата продвижения'),
        ),
    ]
