# Generated by Django 4.2.7 on 2025-12-15 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzmat', '0007_advertisement_is_promoted_advertisement_promoted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='promotion_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Активно до'),
        ),
    ]
