# Generated by Django 4.2.7 on 2025-12-15 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzmat', '0008_advertisement_promotion_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='promotion_plan',
            field=models.CharField(blank=True, choices=[('gold', 'GOLD'), ('premium', 'PREMIUM'), ('vip', 'VIP')], max_length=10, null=True, verbose_name='Тариф продвижения'),
        ),
    ]
