# Generated by Django 4.2.7 on 2025-12-15 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzmat', '0009_advertisement_promotion_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='last_bumped_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последнее поднятие'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Проверенный профиль'),
        ),
        migrations.AddField(
            model_name='user',
            name='verified_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Галочка активна до'),
        ),
    ]
