# Generated by Django 4.2.7 on 2025-12-15 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzmat', '0010_advertisement_last_bumped_at_user_is_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verification_doc1',
            field=models.FileField(blank=True, null=True, upload_to='verification/', verbose_name='Документ 1'),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_doc2',
            field=models.FileField(blank=True, null=True, upload_to='verification/', verbose_name='Документ 2'),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_doc3',
            field=models.FileField(blank=True, null=True, upload_to='verification/', verbose_name='Документ 3'),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_status',
            field=models.CharField(choices=[('none', 'Нет заявки'), ('pending', 'В обработке'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], default='none', max_length=20, verbose_name='Статус верификации'),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_type',
            field=models.CharField(blank=True, choices=[('individual', 'Физическое лицо'), ('company', 'Компания')], max_length=20, null=True, verbose_name='Тип верификации'),
        ),
    ]
