# Generated by Django 4.2.7 on 2025-12-15 10:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uzmat', '0011_user_verification_doc1_user_verification_doc2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_type', models.CharField(choices=[('individual', 'Физическое лицо'), ('company', 'Юридическое лицо')], max_length=20, verbose_name='Тип верификации')),
                ('status', models.CharField(choices=[('pending', 'В обработке'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], default='pending', max_length=20, verbose_name='Статус')),
                ('reviewer_comment', models.TextField(blank=True, null=True, verbose_name='Комментарий модератора')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата решения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_requests', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заявка на верификацию',
                'verbose_name_plural': 'Заявки на верификацию',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VerificationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(blank=True, max_length=50, null=True, verbose_name='Тип документа')),
                ('file', models.FileField(upload_to='verification/requests/', verbose_name='Файл')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='uzmat.verificationrequest', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'Документ верификации',
                'verbose_name_plural': 'Документы верификации',
                'ordering': ['created_at'],
            },
        ),
    ]














