# Generated by Django 5.2.9 on 2025-12-16 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzmat', '0016_badge_renew_reminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatthread',
            name='buyer_last_read_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время последнего прочтения покупателем'),
        ),
        migrations.AddField(
            model_name='chatthread',
            name='seller_last_read_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время последнего прочтения продавцом'),
        ),
    ]
