# Generated by Django migration

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('uzmat', '0017_chatthread_buyer_last_read_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('promotion', 'Продвижение объявления'), ('verification', 'Верификация профиля')], max_length=20, verbose_name='Тип платежа')),
                ('plan', models.CharField(blank=True, choices=[('gold', 'GOLD'), ('premium', 'PREMIUM'), ('vip', 'VIP')], max_length=10, null=True, verbose_name='Тариф продвижения')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма в сумах')),
                ('amount_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Сумма в долларах')),
                ('click_transaction_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID транзакции Click')),
                ('click_payment_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID платежа Click')),
                ('status', models.CharField(choices=[('pending', 'Ожидает оплаты'), ('completed', 'Оплачено'), ('cancelled', 'Отменено'), ('failed', 'Ошибка оплаты')], default='pending', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('ad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='uzmat.advertisement', verbose_name='Объявление')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
                'ordering': ['-created_at'],
            },
        ),
    ]
