# Generated by Django migration

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uzmat', '0018_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
