# Generated by Django 5.2.9 on 2025-12-27 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzmat', '0019_delete_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='currency',
            field=models.CharField(choices=[('kzt', '₸ KZT'), ('uzs', 'сум UZS'), ('rub', '₽ RUB')], default='kzt', max_length=10, verbose_name='Валюта'),
        ),
        migrations.AddIndex(
            model_name='advertisement',
            index=models.Index(fields=['is_promoted', 'promotion_until'], name='uzmat_adver_is_prom_1a166e_idx'),
        ),
        migrations.AddIndex(
            model_name='advertisement',
            index=models.Index(fields=['user', 'is_active'], name='uzmat_adver_user_id_f0da40_idx'),
        ),
        migrations.AddIndex(
            model_name='advertisement',
            index=models.Index(fields=['country', 'city', 'is_active'], name='uzmat_adver_country_5c348a_idx'),
        ),
        migrations.AddIndex(
            model_name='advertisement',
            index=models.Index(fields=['is_active', 'last_bumped_at'], name='uzmat_adver_is_acti_f1bc1c_idx'),
        ),
        migrations.AddIndex(
            model_name='advertisement',
            index=models.Index(fields=['promotion_plan', 'promoted_at'], name='uzmat_adver_promoti_ba3c6f_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['thread', '-created_at'], name='uzmat_chatm_thread__9729a9_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['sender', 'created_at'], name='uzmat_chatm_sender__129849_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['thread', 'id'], name='uzmat_chatm_thread__8e3222_idx'),
        ),
        migrations.AddIndex(
            model_name='chatthread',
            index=models.Index(fields=['buyer', '-last_message_at'], name='uzmat_chatt_buyer_i_1eaa03_idx'),
        ),
        migrations.AddIndex(
            model_name='chatthread',
            index=models.Index(fields=['seller', '-last_message_at'], name='uzmat_chatt_seller__33ec90_idx'),
        ),
        migrations.AddIndex(
            model_name='chatthread',
            index=models.Index(fields=['-last_message_at'], name='uzmat_chatt_last_me_8b35a4_idx'),
        ),
        migrations.AddIndex(
            model_name='chatthread',
            index=models.Index(fields=['advertisement', 'thread_type'], name='uzmat_chatt_adverti_12f9aa_idx'),
        ),
    ]
