# Generated by Django 5.2.9 on 2025-12-31 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzmat', '0020_add_performance_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='price_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Цена в USD'),
        ),
    ]
