# Generated by Django 5.2.9 on 2026-01-18 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzmat', '0021_advertisement_price_usd'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='sent_to_telegram',
            field=models.BooleanField(default=False, verbose_name='Отправлено в Telegram'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='telegram_message_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID сообщения в Telegram'),
        ),
    ]
